# Generated by Django 5.0.6 on 2024-07-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WES', 'western wear'), ('BW', 'Bridal wear'), ('EW', 'Ethnic wear'), ('WIN', 'winter wear'), ('AW', 'Active wear'), ('SW', 'Summer wear')], max_length=4),
        ),
    ]
